### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by haxta4ok00**
Update count products

### CODE REVIEW

**Comment by stacyspiva** [comment]
Thanks @haxta4ok00  for catching this! We've updated the page accordingly

**Comment by haxta4ok00** [comment]
Hey @stacyspiva , yeap, but after you last update, now 5 different products :) not 4

**Comment by stacyspiva** [comment]
good catch! it's fixed now :P

**Comment by haxta4ok00** [comment]
Nice :P !

**Pull request closed without merging**
