### PR TITLE
Add asset types explanations

### PR DESCRIPTION
**Pull request by martijnrusschen**
Adding descriptions for the different asset types we have in our app. We will use this as a reference in our API docs.

### CODE REVIEW

**Comment by stacyspiva** [comment]
hi @martijnrusschen, I'm going to suggest that we don't merge these changes into the article. We already have a page that's specific to asset types here: https://docs.hackerone.com/programs/asset-types.html

What I can do is add the asset types that you've listed that aren't already on the Asset Types article.

And I can add a line after step 4 in the Defining Scope article to say something like, "View all asset types" and then link it to the Asset Types article.

What do you think?

**Comment by martijnrusschen** [comment]
Ah, I didn't see the asset types page. A separate page works even better. However, it seems my PR contains more types than the page is listing right now. Can you make sure the page gets updated with the types I have in my PR? I copied my types directly from what we have in our product.

**Comment by stacyspiva** [comment]
yes, will do!

**Comment by stacyspiva** [comment]
updated https://docs.hackerone.com/programs/asset-types.html with the most up-to-date assets

**Pull request closed without merging**
