### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Shashank-In**
It is upon the program to reward a bounty for the retest. May not be the case all the time.

### CODE REVIEW

**Comment by martijnrusschen** [comment]
@stacyspiva I think we might want to clarify our docs that there are 2 versions of retesting. Hacker Powered retesting where the hacker gets a reward for doing the retest, and triage retesting where the hacker doesn't get a reward since the retest is performed by the triage team.

**Comment by joshuapage2017** [comment]
Embed

**Comment by Shashank-In** [comment]
Hi @martijnrusschen 
Is there a case scenario where a hacker does the retest but does not get paid?

**Comment by martijnrusschen** [comment]
> Hi @martijnrusschen
> Is there a case scenario where a hacker does the retest but does not get paid?

No, in normal circumstances that's no possible. If the retest is done by a hacker (not a pentester) the hacker will always by rewarded for that (except for the cases where the customer isn't satisfied with the effort the hacker took to perform the retest).

**Comment by stacyspiva** [comment]
Closing this PR as in hacker-powered retesting you will be rewarded for a successful retest

**Pull request closed without merging**
