### PR TITLE
Create report-id.md

### PR DESCRIPTION
**Pull request by tolo7010**
Should be listed under "Hackers -> Reports" category

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Hi @tolo7010, thanks for writing this up. I'm struggling a bit with verifying the need to explain how a report ID works. Do you think it's not clear enough, that it needs an article?

**Comment by tolo7010** [comment]
Hi @martijnrusschen, thanks for your comment. This is just an article to be used as a reference or its functions may be extended in the future. However, I'm not really sure if it is too much or uninteresting.

Please feel free to close this, I will try to write more when I have time. Thanks again.

Regards,
tolo7010

**Review by ijlale — APPROVED** [review]

**Review by White66778 — APPROVED** [review]
>

**Review by Fluxy911076 — APPROVED** [review]

**Comment by inosgun** [comment]
T

**Comment by inosgun** [comment]
6yyu

**Pull request closed without merging**
